FROM openjdk:17-jdk-alpine
# install curl
RUN apk add --no-cache curl
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Xms1024m", "-Xmx1024m", "-jar","/app.jar"]
