apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcs-pv
  labels:
    type: gcs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - implicit-dirs
    - uid=100
    - gid=100
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: qwiklabs-gcp-00-05c3d5ba3ae9-bucket
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
      matchLabels:
       type: gcs
