apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-spring-boot-docker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pv-spring-boot-docker
  template:
    metadata:
      labels:
        app: pv-spring-boot-docker
    spec:
      containers:
      - name: pv-spring-boot-docker
        image: javalove93/spring-boot-docker
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.5"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: app-shared-storage
            mountPath: /data
      volumes:
        - name: app-shared-storage
          persistentVolumeClaim:
            claimName: nfs-pvc
